# Sociocultural Implications

Metaverse will bring along as much change as the internet has done for human society years ago. It will create a bond between people from all over the world, but it will also pull people apart.  


When people interact in the metaverse, they bring their own values and culture into the mix. If people are allowed to design an outfit for themselves in the metaverse, some people may be inclined to wear something that they would normally be too embarrassed to wear. They might go for traditional outfits, or flashy ones that are very expressive of the individual’s personality. In a way, Metaverse, like the internet, allows people to be different, and embrace the difference. Metaverse will eventually form sub-cultures of its own, like the internet did over the years. It will be “used as a route to access a community, to influence their experiences and it can also be a means of social communion, just like the TV and radio before it.” Countless new ideas and values will merge and form a cultural norm strictly in the context of metaverse. 


Metaverse will break down the geographical barriers in the real world, and create a universe without boundaries for people from different backgrounds. It brings about the interaction and overlay between the real and the digital. Like how the internet broke down barriers many years ago, the metaverse is only going to magnify this effect. With VR technology, it will make sharing much easier and realistic.  Right now we can only share pictures and videos. but with the help of VR headsets, other people can experience your content in 3D view. This will almost be like a more accessible and affordable traveling method. As a result, people can get to experience different countries, languages, cultures, and traditions without even stepping foot out of their house. 
