# Burnout and Health Effects

## Avoiding Burnout

**Create a dedicated work space in the Metaverse**

In order to set boundaries between work and daily life, people should only put on the working headsets and accessories in a dedicated area of the room. By doing so, people would need to go to the workroom and start working. If the working headsets are put in the relaxing area of the room, people may casually start working, and it will be very hard to set boundaries. If you don’t have clear boundaries, your entire house will end up becoming a work space, even after hours.


**Set working hours and strictly follow the schedule**

In remote work space, it is very easy for people to lose track of time, and the condition may be worse in the Metaverse. In a highly realistic Metaverse work space, people may not notice at the end of a work day, and continue to work after hours unintentionally. Therefore, it is crucial to have strict work hours, and be intentional about it. Although people tend to focus a lot on all their work, people need to keep track of time to avoid burnout.


## Dealing with Health Side Effects

Similar to gaming and social media, using VR too much will likely lead to behavioral addiction. The user or their family/friends would notice that the user’s quality of life is now suffering because of them being involved in VR. The addiction problem may take the form of ignoring everyday tasks, not wanting to engage with family/friends in real life, and getting frustrated when the user doesn't get to use VR. Behavioral addiction can then lead to more mental health issues like mood disorder, stress, depression, and physical health issues like nausea, dizziness, disorientation, motion sickness. 

In order to step out of the negative loop, we suggest that users set a time limit to VR usage everyday. We suggest that the user’s friend or family member should take away the hardware when the time limit is up, so that the user will not be tempted to continue using it. We recommend that the user incorporates time for exercises or other activities that do not involve sitting down staring at the screen. Taking a walk outside, going to the gym, or simply hanging out with friends outside will be immensely beneficial to the user’s mental health. If the user’s addiction problem becomes increasingly out of control, we recommend the user get professional therapy. 

**If you are currently suffering from any sort of behavioral addiction, please refer to this website for professional guidance:** [SAMHSA](https://www.samhsa.gov/find-help/national-helpline)





